### ISSUE TITLE
更换组件内颜色 

### ISSUE THREAD

**Issue by Shenchuanhuan** [shulie/dh-component#60]
需更换 dh-tab-nav内的三个按钮选中状态的颜色，现在为 #3ab86e，更换值为： #23c132

**Comment by JerryBerton** [comment]
此问题已解决， 谢谢您的良好意见，欢迎继续关注datahunter前端开发团队的公共项目

**Comment by lanyuechen** [comment]
Oh! This is a very good react component, I use it in my project and it help me raising my speed. so can I join your project? waiting your response, thank u
